[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 1

# needed for Bera tests, they read a .json for validator data
fs_permissions = [
	{ access = "read", path = "./test" },
	{ access = "read", path = "./script" },
]

# 2025-01-02 (Thursday)
block_timestamp = 1735776000


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
